#!/bin/ksh

cd "${0%/*}"

BINDIR=`pwd`
ROOTDIR="${BINDIR}/.."
CONFDIR="${ROOTDIR}/conf"
LIBDIR="${ROOTDIR}/lib"

pidFile=${BINDIR}/indra.pid

INDRA_JAVA_OPTS=${INDRA_JAVA_OPTS:--Xmx4g}
echo "INDRA_JAVA_OPTS: ${INDRA_JAVA_OPTS}"

cmd="java -jar -server ${INDRA_JAVA_OPTS} \
-Djava.net.preferIPv4Stack=true \
-Dfile.encoding=UTF-8 \
-Dlogback.configurationFile=${CONFDIR}/logback.xml \
${LIBDIR}/${project.artifactId}-${project.version}.jar $@ ../conf/indra.yaml"


eval "${cmd}"



